Include unit tests in konflux pull_request
podengo-project/idmsvc-frontend pull request #108
Opened 2024-10-24 06:23 UTC by mshriver

The configuration will need tuning to set resource requests. 

Resource limits pulled from https://github.com/RedHatInsights/compliance-frontend/pull/2217/commits/67e45519714010d5eb524f8af5b17afd31741005

2024-10-24 08:28 UTC, avisiedo commented
@mshriver  Build is failing with:

```
subprocess exited with status 1
subprocess exited with status 1
Error: building at STEP "RUN npm install": exit status 1
```

On `build-container` task; make me think related with this: https://github.com/podengo-project/idmsvc-frontend/blob/main/.tekton/idmsvc-frontend-pull-request.yaml#L346

But unsure the root cause.

2024-10-24 14:26 UTC, mshriver commented
/retest

2024-10-24 16:42 UTC, avisiedo requested changes
@mshriver  thanks for the change

The pipeline seems to work with the last execution.

Only I observed one suggested change, after that, it is a LFTM

2024-10-24 16:42 UTC, avisiedo commented on deploy/frontend.yaml
> +>>>>>>> 4faa71f (Move ClowdApp to Konflux image)
```suggestion
    value: quay.io/redhat-services-prod/insights-management-tenant/insights-idmsvc/idmsvc-frontend
```

2024-10-25 03:26 UTC, frasertweedale commented
I fixed that merge issue and rebased.

2024-10-25 03:33 UTC, frasertweedale approved these changes

2024-10-25 03:34 UTC, merged