fix(HMS-4023): paging and reduce number of API requests
podengo-project/idmsvc-frontend pull request #54
Opened 2024-04-29 08:19 UTC by pvoborni

**fix(HMS-4023): paging and reduce number of API requests**

Before, to load data for list page the UI did:
- 2x `domains?offest=0&limit=10` call
- a `readDomain` call for each returned domain

I.e. max 22 calls if the account has 10+ domains or
4 calls with a single domain.

Another issue was that the order of displayed domains was not stable.
Domains were added to appContext domain in order of finishing
asynchronous request. Thus it changed on each refresh.

Paging did not work as setting page and perPage was not propagated
well to the API call.

Now there is only single `domains?offset=$offset&limit=$pageSize` call
as this call returns all the data required for list page.

AppContext was extended to tracked results from `readDomain` and from
`domains` call separately. But `updateDomain`, `deleteDomain` calls were
changed so that they would update both list - to reflect deletion or
enable/disable of domain right away without reload of domains.

**fix: harden details page**

To handle when:
- domain is not in appContext

To navigate to domains list when:
- domain id is not supplied
- domain id is not for valid domain

A prep for HMS-4023

2024-04-29 16:05 UTC, avisiedo requested changes
Thanks for the change; I liked the deduplication of some changes, and I have learned how to use in a more efficient way the language properties.

Checked the behavior locally, and the requests are dramatically reduced; :+1: 

After a minor change, it will be a LGTM.

2024-04-30 07:11 UTC, pvoborni commented on src/Routes/DefaultPage/DefaultPage.tsx
> +                onPerPageSelect={(event, perPage) => setPerPage(perPage)}
Fixed.

In this case correct is with underscore as the values is not used and that is the common pattern to declare it as unused - when it needs to be present as the following param is used.   If neither param was used then it is better to remove them all. 

I think that eslint can be configured to raise warning/error for this case.

2024-04-30 07:11 UTC, pvoborni commented on src/Routes/DefaultPage/DefaultPage.tsx
> +interface DomainListProps {
thanks, fixed.

2024-04-30 07:12 UTC, pvoborni commented on src/Routes/DefaultPage/DefaultPage.tsx
> +const ListContent = (props: DomainListProps) => {
thanks, fixed.

2024-04-30 08:12 UTC, avisiedo approved these changes
changes and concerns resolved! :+1:

LGTM

2024-04-30 08:16 UTC, merged